[package]
name = "aceforthlib"
workspace = ".."
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
iz80 = "^0.4.3"
miniz_oxide = "0.8.2"
image = "^0.25.5"




